/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayersUserIdRouteImport } from './routes/players/$userId'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthStatsRouteImport } from './routes/_auth/stats'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthFriendsRouteImport } from './routes/_auth/friends'
import { Route as AuthChallengesRouteImport } from './routes/_auth/challenges'
import { Route as AuthAchievementsRouteImport } from './routes/_auth/achievements'
import { Route as AuthRoomsIndexRouteImport } from './routes/_auth/rooms/index'
import { Route as AuthRoomsJoinRouteImport } from './routes/_auth/rooms/join'
import { Route as AuthRoomsCreateRouteImport } from './routes/_auth/rooms/create'
import { Route as AuthRoomsRoomIdRouteImport } from './routes/_auth/rooms/$roomId'
import { Route as AuthGameWordquizGameIdRouteImport } from './routes/_auth/game/wordquiz.$gameId'
import { Route as AuthGameUndercoverGameIdRouteImport } from './routes/_auth/game/undercover.$gameId'
import { Route as AuthGameMcqquizGameIdRouteImport } from './routes/_auth/game/mcqquiz.$gameId'
import { Route as AuthGameCodenamesGameIdRouteImport } from './routes/_auth/game/codenames.$gameId'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersUserIdRoute = PlayersUserIdRouteImport.update({
  id: '/players/$userId',
  path: '/players/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStatsRoute = AuthStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFriendsRoute = AuthFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChallengesRoute = AuthChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAchievementsRoute = AuthAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRoomsIndexRoute = AuthRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRoomsJoinRoute = AuthRoomsJoinRouteImport.update({
  id: '/rooms/join',
  path: '/rooms/join',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRoomsCreateRoute = AuthRoomsCreateRouteImport.update({
  id: '/rooms/create',
  path: '/rooms/create',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRoomsRoomIdRoute = AuthRoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGameWordquizGameIdRoute = AuthGameWordquizGameIdRouteImport.update({
  id: '/game/wordquiz/$gameId',
  path: '/game/wordquiz/$gameId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGameUndercoverGameIdRoute =
  AuthGameUndercoverGameIdRouteImport.update({
    id: '/game/undercover/$gameId',
    path: '/game/undercover/$gameId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthGameMcqquizGameIdRoute = AuthGameMcqquizGameIdRouteImport.update({
  id: '/game/mcqquiz/$gameId',
  path: '/game/mcqquiz/$gameId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGameCodenamesGameIdRoute = AuthGameCodenamesGameIdRouteImport.update({
  id: '/game/codenames/$gameId',
  path: '/game/codenames/$gameId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/leaderboard': typeof LeaderboardRoute
  '/privacy': typeof PrivacyRoute
  '/achievements': typeof AuthAchievementsRoute
  '/challenges': typeof AuthChallengesRoute
  '/friends': typeof AuthFriendsRoute
  '/profile': typeof AuthProfileRoute
  '/stats': typeof AuthStatsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/players/$userId': typeof PlayersUserIdRoute
  '/rooms/$roomId': typeof AuthRoomsRoomIdRoute
  '/rooms/create': typeof AuthRoomsCreateRoute
  '/rooms/join': typeof AuthRoomsJoinRoute
  '/rooms/': typeof AuthRoomsIndexRoute
  '/game/codenames/$gameId': typeof AuthGameCodenamesGameIdRoute
  '/game/mcqquiz/$gameId': typeof AuthGameMcqquizGameIdRoute
  '/game/undercover/$gameId': typeof AuthGameUndercoverGameIdRoute
  '/game/wordquiz/$gameId': typeof AuthGameWordquizGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/leaderboard': typeof LeaderboardRoute
  '/privacy': typeof PrivacyRoute
  '/achievements': typeof AuthAchievementsRoute
  '/challenges': typeof AuthChallengesRoute
  '/friends': typeof AuthFriendsRoute
  '/profile': typeof AuthProfileRoute
  '/stats': typeof AuthStatsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/players/$userId': typeof PlayersUserIdRoute
  '/rooms/$roomId': typeof AuthRoomsRoomIdRoute
  '/rooms/create': typeof AuthRoomsCreateRoute
  '/rooms/join': typeof AuthRoomsJoinRoute
  '/rooms': typeof AuthRoomsIndexRoute
  '/game/codenames/$gameId': typeof AuthGameCodenamesGameIdRoute
  '/game/mcqquiz/$gameId': typeof AuthGameMcqquizGameIdRoute
  '/game/undercover/$gameId': typeof AuthGameUndercoverGameIdRoute
  '/game/wordquiz/$gameId': typeof AuthGameWordquizGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/leaderboard': typeof LeaderboardRoute
  '/privacy': typeof PrivacyRoute
  '/_auth/achievements': typeof AuthAchievementsRoute
  '/_auth/challenges': typeof AuthChallengesRoute
  '/_auth/friends': typeof AuthFriendsRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/stats': typeof AuthStatsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/players/$userId': typeof PlayersUserIdRoute
  '/_auth/rooms/$roomId': typeof AuthRoomsRoomIdRoute
  '/_auth/rooms/create': typeof AuthRoomsCreateRoute
  '/_auth/rooms/join': typeof AuthRoomsJoinRoute
  '/_auth/rooms/': typeof AuthRoomsIndexRoute
  '/_auth/game/codenames/$gameId': typeof AuthGameCodenamesGameIdRoute
  '/_auth/game/mcqquiz/$gameId': typeof AuthGameMcqquizGameIdRoute
  '/_auth/game/undercover/$gameId': typeof AuthGameUndercoverGameIdRoute
  '/_auth/game/wordquiz/$gameId': typeof AuthGameWordquizGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/leaderboard'
    | '/privacy'
    | '/achievements'
    | '/challenges'
    | '/friends'
    | '/profile'
    | '/stats'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/players/$userId'
    | '/rooms/$roomId'
    | '/rooms/create'
    | '/rooms/join'
    | '/rooms/'
    | '/game/codenames/$gameId'
    | '/game/mcqquiz/$gameId'
    | '/game/undercover/$gameId'
    | '/game/wordquiz/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/leaderboard'
    | '/privacy'
    | '/achievements'
    | '/challenges'
    | '/friends'
    | '/profile'
    | '/stats'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/players/$userId'
    | '/rooms/$roomId'
    | '/rooms/create'
    | '/rooms/join'
    | '/rooms'
    | '/game/codenames/$gameId'
    | '/game/mcqquiz/$gameId'
    | '/game/undercover/$gameId'
    | '/game/wordquiz/$gameId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/about'
    | '/leaderboard'
    | '/privacy'
    | '/_auth/achievements'
    | '/_auth/challenges'
    | '/_auth/friends'
    | '/_auth/profile'
    | '/_auth/stats'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/players/$userId'
    | '/_auth/rooms/$roomId'
    | '/_auth/rooms/create'
    | '/_auth/rooms/join'
    | '/_auth/rooms/'
    | '/_auth/game/codenames/$gameId'
    | '/_auth/game/mcqquiz/$gameId'
    | '/_auth/game/undercover/$gameId'
    | '/_auth/game/wordquiz/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PrivacyRoute: typeof PrivacyRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  PlayersUserIdRoute: typeof PlayersUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$userId': {
      id: '/players/$userId'
      path: '/players/$userId'
      fullPath: '/players/$userId'
      preLoaderRoute: typeof PlayersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/stats': {
      id: '/_auth/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthStatsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/friends': {
      id: '/_auth/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthFriendsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/challenges': {
      id: '/_auth/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AuthChallengesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/achievements': {
      id: '/_auth/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthAchievementsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/rooms/': {
      id: '/_auth/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof AuthRoomsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/rooms/join': {
      id: '/_auth/rooms/join'
      path: '/rooms/join'
      fullPath: '/rooms/join'
      preLoaderRoute: typeof AuthRoomsJoinRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/rooms/create': {
      id: '/_auth/rooms/create'
      path: '/rooms/create'
      fullPath: '/rooms/create'
      preLoaderRoute: typeof AuthRoomsCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/rooms/$roomId': {
      id: '/_auth/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof AuthRoomsRoomIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/game/wordquiz/$gameId': {
      id: '/_auth/game/wordquiz/$gameId'
      path: '/game/wordquiz/$gameId'
      fullPath: '/game/wordquiz/$gameId'
      preLoaderRoute: typeof AuthGameWordquizGameIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/game/undercover/$gameId': {
      id: '/_auth/game/undercover/$gameId'
      path: '/game/undercover/$gameId'
      fullPath: '/game/undercover/$gameId'
      preLoaderRoute: typeof AuthGameUndercoverGameIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/game/mcqquiz/$gameId': {
      id: '/_auth/game/mcqquiz/$gameId'
      path: '/game/mcqquiz/$gameId'
      fullPath: '/game/mcqquiz/$gameId'
      preLoaderRoute: typeof AuthGameMcqquizGameIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/game/codenames/$gameId': {
      id: '/_auth/game/codenames/$gameId'
      path: '/game/codenames/$gameId'
      fullPath: '/game/codenames/$gameId'
      preLoaderRoute: typeof AuthGameCodenamesGameIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAchievementsRoute: typeof AuthAchievementsRoute
  AuthChallengesRoute: typeof AuthChallengesRoute
  AuthFriendsRoute: typeof AuthFriendsRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthStatsRoute: typeof AuthStatsRoute
  AuthRoomsRoomIdRoute: typeof AuthRoomsRoomIdRoute
  AuthRoomsCreateRoute: typeof AuthRoomsCreateRoute
  AuthRoomsJoinRoute: typeof AuthRoomsJoinRoute
  AuthRoomsIndexRoute: typeof AuthRoomsIndexRoute
  AuthGameCodenamesGameIdRoute: typeof AuthGameCodenamesGameIdRoute
  AuthGameMcqquizGameIdRoute: typeof AuthGameMcqquizGameIdRoute
  AuthGameUndercoverGameIdRoute: typeof AuthGameUndercoverGameIdRoute
  AuthGameWordquizGameIdRoute: typeof AuthGameWordquizGameIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAchievementsRoute: AuthAchievementsRoute,
  AuthChallengesRoute: AuthChallengesRoute,
  AuthFriendsRoute: AuthFriendsRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthStatsRoute: AuthStatsRoute,
  AuthRoomsRoomIdRoute: AuthRoomsRoomIdRoute,
  AuthRoomsCreateRoute: AuthRoomsCreateRoute,
  AuthRoomsJoinRoute: AuthRoomsJoinRoute,
  AuthRoomsIndexRoute: AuthRoomsIndexRoute,
  AuthGameCodenamesGameIdRoute: AuthGameCodenamesGameIdRoute,
  AuthGameMcqquizGameIdRoute: AuthGameMcqquizGameIdRoute,
  AuthGameUndercoverGameIdRoute: AuthGameUndercoverGameIdRoute,
  AuthGameWordquizGameIdRoute: AuthGameWordquizGameIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  LeaderboardRoute: LeaderboardRoute,
  PrivacyRoute: PrivacyRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  PlayersUserIdRoute: PlayersUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
